services:
  ion.server:
    build: .
    container_name: ion.app
    ports:
      - "80:8080"
        
    depends_on: 
      - sql
  
  ion.api:
    build: ./
    container_name: ion.api
    ports:
      - "5000:8080"
    
    depends_on: 
      - ion.server
  
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: A&VeryComplex123Password